import type { CaseStudy } from "./directus";

export const caseStudiesFallback: Record<string, CaseStudy> = {

  "smart-catering": {
    id: 1, status: "published", slug: "smart-catering",
    date_created: "2024-11-01T00:00:00Z",
    title: "Case Study: Smart Catering",
    subtitle: "Markenaufbau & Digitalisierung in der Betriebsgastronomie",
    description: "Wie ein Leistungsbereich der Sander Gruppe zur eigenständigen Marke wurde – durch Sprache, Struktur und Gestaltung.",
    excerpt: "Smart Catering machte ein bestehendes Portfolio durch Sprache, Struktur und Gestaltung sichtbar.",
    kunde: "Sander Gruppe / Smart Catering",
    branche: "Betriebsgastronomie",
    tags: "Markenaufbau, Designsystem, Automatisierung",
    hero_image: undefined,
    kunde_logo: undefined,
    intro_text: "Der Bereich Betriebsgastronomie der Sander Gruppe verfügte über ein starkes Leistungsangebot. Was fehlte, war eine Marke, die es für Entscheider sichtbar macht, mit einer klaren Sprache, einer modularen Angebotsstruktur und einer Gestaltung, die beides trägt. So entstand Smart Catering: nicht als neues Unternehmen, sondern als eigenständige Positionierung eines Leistungsbereichs, der bereits existierte.",
    ausgangslage_text: "Smart Catering verfügte über hohe operative Kompetenz, ein starkes Leistungsportfolio und jahrzehntelange Erfahrung. Was fehlte, war keine Leistung, sondern eine Sprache dafür.\n\nDie Kommunikation orientierte sich am Erlebnis der Mitarbeitenden. Die eigentlichen Entscheider – Geschäftsführung, HR, Facility-Management – wurden nicht präzise adressiert. Das Angebot war intern logisch, aber nicht aus der Perspektive derer strukturiert, die es beauftragen.\n\nDie zentrale Herausforderung: Wie wird ein komplexes Leistungsangebot so aufbereitet, dass Entscheider es schnell erfassen, bewerten und strategisch einordnen können?",
    ziele_left_title: "Marke, Positionierung & Kommunikation",
    ziele_left_text: "- Entwicklung von Smart Catering als eigenständige Marke mit klarer Struktur, eigenem Wording und konsistenter Argumentationslogik\n- Zielgruppengerechte Ansprache von Entscheidern – Geschäftsführung, HR, Facility-Management – mit Fokus auf Wirtschaftlichkeit, Implementierung und Prozesssicherheit\n- Explizite Formulierung impliziter Mehrwerte, um operative Stärke nachvollziehbar und bewertbar zu machen\n- Ersatz emotionaler Narrative durch eine klare, lösungsorientierte Argumentationslogik",
    ziele_right_title: "Struktur, System & Befähigung",
    ziele_right_text: "- Strukturierung des Leistungsangebots in eine modulare, nachvollziehbare Angebotsarchitektur, die Entscheidungsprozesse vereinfacht\n- Einführung eines konsistenten, skalierbaren Designsystems für Angebotsproduktion, Präsentation und Markenführung\n- Pragmatische Digitalisierung zentraler Arbeitsprozesse mit unmittelbar spürbarem Nutzen\n- Kompetenzaufbau im Unternehmen für langfristige, eigenständige Weiterentwicklung",
    vorgehen_items: [
      { title: "Informations-Architektur & UX-Logik", text: "Bevor Strukturen entstehen, muss verstanden werden, was das Angebot wirklich leistet. Dieses Zuhören ist keine Vorstufe, es ist die Grundlage. Oft entsteht hier eine Formulierung des Mehrwertes, die dem Unternehmen selbst noch nicht in dieser Klarheit bewusst war.\n\nAuf dieser Basis entsteht eine Architektur nach Prinzipien aus UX-Design und SEO: Hierarchische Gliederung und modulare Struktur, logische Progression und konsistente Benennung, durchgängige Navigationslogik innerhalb der Dokumente.\n\nKomplexität wird nicht verkürzt, sie wird strukturiert. Ein Entscheider darf nie verloren gehen." },
      { title: "Answer-First-Strukturierung", text: "Die Angebotslogik folgt einem klaren Prinzip: Die zentrale Antwort steht zuerst, Details folgen in strukturierter Vertiefung. Jede Ebene beantwortet eine konkrete Frage.\n\nBekannt aus SEO und Content-Strategie wird hier konsequent auf Angebots- und Präsentationsdokumente übertragen." },
      { title: "Form Follows Function", text: "Gestaltung ist ein Werkzeug, keine Dekoration. Das Figma-Designsystem macht diesen Ansatz technisch greifbar: Modulare, wiederverwendbare Bausteine, konsistente Markenführung über alle Vertriebskanäle, kundenindividuelle Anpassbarkeit in Echtzeit, kein Dateichaos, kein Versionsdurcheinander.\n\nVisuelle Sprache, die Kompetenz vermittelt – nicht solche, die sie übertüncht." },
      { title: "Digitalisierung als Prozessstrategie", text: "Digitalisierung beginnt dort, wo tatsächlich gearbeitet wird – nicht im System, sondern im Prozess. An realen Reibungspunkten ansetzen, sofort spürbaren Nutzen schaffen, Akzeptanz durch Erleben, nicht durch Überzeugungsarbeit.\n\nWenn Werkzeuge sinnvoll integriert werden, verändert sich das Arbeiten selbst. Digitalisierung wird Teil der Praxis – nicht des Programms." },
    ],
    ergebnis_text: "Smart Catering existierte als Leistung. Jetzt existiert es als Marke mit einer Sprache, einer Struktur und einer Gestaltung, die Entscheider direkt adressiert. Die Grundlage für den Vertrieb ist gelegt. Die nächste Phase beginnt.\n\n- Komplexe Angebotswelten werden durch Struktur beherrschbar.\n- Zielgruppenorientierung entscheidet über Positionierung.\n- Wenn Inhalt nicht strukturiert ist, kann Design ihn nicht retten.\n- Digitalisierung beginnt im Prozess, nicht im System.\n- Nachhaltige Transformation entsteht durch Kompetenzaufbau.",
    kpis: [],
  },

  "portazon": {
    id: 2, status: "published", slug: "portazon",
    date_created: "2024-10-01T00:00:00Z",
    title: "Case Study: Portazon – Smart City Super App",
    subtitle: "Zusammenarbeit mit Stadtwerken Trier und A EINS Business Intelligence GmbH",
    description: "Zur Digitalisierung der Region Trier: Eine Super-App mit E-Auto-Laden, Parken, Deutschland-Ticket, Marktplatz-Shopping und digitalem Kundencenter.",
    excerpt: "70.000+ Downloads, 1 Mio.+ Interaktionen – wie Portazon zur regionalen Super-App wurde.",
    kunde: "Portazon / Stadtwerke Trier",
    branche: "Smart City / Digitalplattform",
    tags: "SEO / GEO, Markenaufbau, Automatisierung",
    hero_image: undefined,
    kunde_logo: undefined,
    intro_text: "In Zusammenarbeit mit den Stadtwerken Trier (SWT) und dem Digitalunternehmen A EINS Business Intelligence GmbH wurde die Portazon Smart City Super App entwickelt, die Services wie E-Auto-Laden, Parken, Deutschland-Ticket, Marktplatz-Shopping und Digitales Kundencenter der SWT in einer App vereint. Diese Investition dient insbesondere der Digitalisierung der Stadt Trier und der Region. DigiPub unterstützte den strategischen Aufbau, die Sichtbarkeitssteigerung und die Content- sowie Digitalstrategie für nachhaltiges Wachstum.",
    ausgangslage_text: "- Beta-Phase ohne stabile Nutzerbasis\n- Fehlende Priorisierung für Feature-Entwicklung\n- Nicht eingebundene Partner\n- Schleppende Nutzergewinnung\n- Unkonkrete Skalierungsstrategie\n- Geringe Markenbekanntheit regional\n- Fehlende Online-Offline-Strategie",
    ziele_left_title: "Sichtbarkeit & Wachstum",
    ziele_left_text: "- SEO-basierte Sichtbarkeit aufbauen\n- Conversion maximieren (App-Downloads, aktive Nutzung)\n- Markenbekanntheit in allen Lebensbereichen der Stadtbewohner",
    ziele_right_title: "Partner & Skalierung",
    ziele_right_text: "- Partnergewinnung und Onboarding\n- Online-Offline-Konversionsstrategie entwickeln\n- Skalierungsstrategie für die Region",
    vorgehen_items: [
      { title: "Kategorien-Management", text: "Markt- und Umfeldanalysen, Identifikation lokaler Interessen, digitale Mehrwertabbildung, Anbieter-Identifikation, Kategorie- und Themenbereiche-Definition." },
      { title: "Content-Management", text: "Content-Integration mit SWT.de, Erstellung für Web, Social Media und App. Aufbau nachhaltiger Content-Teams und Redaktionsprozesse. SEO-Content zu Lifestyle, Events und Regionalem." },
      { title: "Partner-Management & Stakeholder", text: "Zusammenarbeit mit Uni Trier, Hochschulen, Trier Marketing. Partnergewinnung und strukturiertes Onboarding." },
      { title: "Kampagnensteuerung", text: "Meta Ads, Google Ads, Copywriting. Monitoring via Firebase, GTM, GA, GSC, Looker Studio." },
    ],
    ergebnis_text: "- Erfolgreicher App-Launch als regionale Super-App\n- Sichtbarkeits- und Markenaufbau realisiert\n- Regionale Markenposition etabliert\n- Online-Offline-Conversion umgesetzt",
    kpis: [
      { value: "70.000+", label: "App-Downloads" },
      { value: "1 Mio.+", label: "Interaktionen" },
      { value: "↑ stabil", label: "Sichtbarkeit" },
    ],
  },

  "haidacher": {
    id: 3, status: "published", slug: "haidacher",
    date_created: "2024-03-01T00:00:00Z",
    title: "Case Study: Tischlerei Haidacher",
    subtitle: "Wie wir der Tischlerei Haidacher halfen, ohne Veränderung des Markenauftritts digital sichtbar zu werden.",
    description: "Markantes, ästhetisches Design – aber kaum Suchmaschinen-Sichtbarkeit. Mit gezieltem SEO änderte sich das in drei Monaten.",
    excerpt: "Klicks von 137 auf 300 in 3 Monaten – ohne eine einzige Designänderung.",
    kunde: "Tischlerei Haidacher",
    branche: "Tischlerei / Innenausbau (Südtirol)",
    tags: "SEO / GEO",
    hero_image: undefined,
    kunde_logo: undefined,
    intro_text: "Die Tischlerei Haidacher aus Südtirol steht für hochwertige Handwerksarbeit und ästhetisches Design. Was fehlte, war digitale Sichtbarkeit: Trotz exzellenter Arbeit fanden potenzielle Kunden – insbesondere Innendesigner und Architekten – das Unternehmen kaum über Suchmaschinen. Das Ziel: mehr Reichweite ohne Eingriff in den bestehenden Markenauftritt.",
    ausgangslage_text: "- Markantes, ästhetisches Design, aber mangelnde Suchmaschinen-Sichtbarkeit\n- Inhalte ohne ausreichende Keyword-Abdeckung für relevante Suchbegriffe\n- Bilder nicht indexiert und in der Bildersuche nicht auffindbar",
    ziele_left_title: "Sichtbarkeit & Keywords",
    ziele_left_text: "- Erhöhung der Sichtbarkeit in Google für hochwertige Suchbegriffe im Innenausbau\n- Verwendung fachlicher Sprache zur Ansprache von Innendesignern und Architekten\n- Snippet-Optimierung zur besseren Auffindbarkeit",
    ziele_right_title: "Bild-SEO & Indexierung",
    ziele_right_text: "- Indexierung und fachliche Beschreibung der Bilder\n- Fachlich präzise Alt-Tags für alle relevanten Bilder\n- Indexierungsmanagement aufbauen",
    vorgehen_items: [
      { title: "Workshop mit der Tischlerei Haidacher", text: "SEO-Grundlagen und Möglichkeiten ohne Designänderungen erläutert. Sensibilisierung für Snippets, Bild-SEO und Keywords." },
      { title: "Snippet-Optimierung", text: "Entwicklung eines Keyword-Sets in Fachsprache für die Zielgruppe. Erstellung optimierter HTML-Titel und Meta Descriptions." },
      { title: "Bild-SEO & Indexierung", text: "Fachlich präzise Formulierung von Alt-Tags für Bilder. Indexierung der Bilder für die Google Bildersuche." },
    ],
    ergebnis_text: "- Verbesserte organische Sichtbarkeit ohne Markenpräsenz-Veränderung\n- Erstmalig fachlich relevante Keyword-Rankings erzielt\n- Relevante Snippets verbessern Auffindbarkeit nachhaltig\n- Indexierte Bilder als zusätzlicher Sichtbarkeitstreiber\n- Ansprache von Innendesignern und Architekten gestärkt\n- Team befähigt, neue Projekte SEO-optimiert anzulegen",
    kpis: [
      { value: "137 → 300", label: "Klicks in 3 Monaten" },
    ],
  },

  "walter-de-gruyter": {
    id: 4, status: "published", slug: "walter-de-gruyter",
    date_created: "2023-06-01T00:00:00Z",
    title: "Technisches SEO & Headless CMS für Walter De Gruyter",
    subtitle: "SEO-optimiertes Content-Management, Headless CMS-Aufbau und technische SEO-Analyse",
    description: "Wie wir De Gruyter beim Content-Management, dem Aufbau eines Headless CMS und der CMS-Auswahl durch eine technische SEO-Analyse unterstützt haben.",
    excerpt: "Stabiles Content-Management und technisches SEO-Fundament für einen der führenden Wissenschaftsverlage.",
    kunde: "Walter De Gruyter",
    branche: "Wissenschaftsverlage / Publishing",
    tags: "SEO / GEO, Automatisierung",
    hero_image: undefined,
    kunde_logo: undefined,
    intro_text: "De Gruyter, einer der führenden Wissenschaftsverlage, benötigte in einer Wachstums- und Transformationsphase Unterstützung beim SEO-optimierten Content-Management, beim Aufbau eines Headless CMS zur effizienteren Content-Pflege sowie bei der Auswahl eines neuen CMS-Systems, für das DigiPub eine umfassende technische SEO-Analyse durchführte. Ziel war es, stabile, nachhaltige Sichtbarkeit aufzubauen, Content-Prozesse effizient abzuwickeln und die Weichen für eine zukunftssichere digitale Infrastruktur zu stellen.",
    ausgangslage_text: "- Fehlende interne Kapazitäten für tägliche Content-Verwaltung\n- Veraltete Prozesse und CMS-Beschränkungen verhinderten effektive Content-Erstellung\n- Notwendigkeit einer fundierten CMS-Neubewertung\n- Risiko von Sichtbarkeitsverlust durch technische SEO-Mängel",
    ziele_left_title: "Content & Prozesse",
    ziele_left_text: "- Tagesaktuelle, optimierte Content-Verwaltung etablieren\n- Flexible, effiziente Content-Produktionsumgebung aufbauen\n- CMS-Auswahl durch technische SEO-Analyse unterstützen",
    ziele_right_title: "SEO & Sichtbarkeit",
    ziele_right_text: "- Digitale Sichtbarkeit und Markenpräsenz stärken\n- Technische SEO-Mängel identifizieren und beheben\n- Langfristige SEO-Grundlage schaffen",
    vorgehen_items: [
      { title: "SEO-optimiertes Content-Management", text: "Projektmanagement zur Anforderungssteuerung, tägliche Content-Verwaltung im bestehenden CMS, SEO-Optimierung vor Veröffentlichung." },
      { title: "Headless CMS mit Craft CMS", text: "Visuelle Content-Verwaltung entwickelt (mit Welance GmbH). HTML-Export/Import-Funktionalität, vereinfachte Produktions- und Vorschauprozesse." },
      { title: "Technische SEO-Analyse", text: "Analyse von Indexierung, Duplicate Content, Canonicals, Ladezeiten. Strukturierte Daten, Meta-Tags, Überschriftenstruktur evaluiert. Handlungsempfehlungen abgeleitet." },
    ],
    ergebnis_text: "- Stabile, tagesaktuelle Content-Verwaltung etabliert\n- Effiziente und visuelle Content-Produktion dank Headless CMS\n- Technische SEO-Anforderungen frühzeitig erkannt\n- Technisches SEO ist entscheidend für CMS-Auswahl und Plattformstrategie",
    kpis: [],
  },
};

export const caseStudiesOrder = ["smart-catering", "portazon", "haidacher", "walter-de-gruyter", "initiative-handarbeit"];
